# =========================
# KITTY — BLACK
# =========================

font_family JetBrainsMono Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto
font_size 14

# Window
background #000000
foreground #eeeeee

background_opacity 0.75
dynamic_background_opacity yes


hide_window_decorations yes

# Cursor
cursor #ffffff
cursor_text_color #000000
cursor_shape beam
cursor_blink_interval 0.5

# Selection
selection_background #333333
selection_foreground #ffffff

# =========================
# ANSI COLORS
# =========================

color0  #000000
color1  #ff5555
color2  #50fa7b
color3  #f1fa8c
color4  #8be9fd
color5  #bd93f9
color6  #8be9fd
color7  #bbbbbb

color8  #555555
color9  #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #a4ffff
color13 #d6acff
color14 #a4ffff
color15 #ffffff

# =========================
# TABS
# =========================

tab_bar_style powerline
tab_powerline_style slanted

active_tab_foreground #000000
active_tab_background #ffffff

inactive_tab_foreground #777777
inactive_tab_background #111111

tab_separator " "

# =========================
# MISC
# =========================

enable_audio_bell no
visual_bell_duration 0.0
confirm_os_window_close 0

url_color #aaaaaa
url_style straight

allow_remote_control yes
