font_family = "JetBrains Mono"
font_size = 12

background = 0xFF000000
base = 0xFF000000
base_secondary = 0xFF000000
text = 0xFFFFFFFF
accent = 0xFF008866
accent_secondary = 0xFF008866
rounding_large = 5
