
# =====================
# Hyprland config
# =====================

$mainMod = SUPER

# ---------------------
# Apps
# ---------------------

# Launcher
bind = $mainMod, D, exec, wofi --show drun

# Terminal
bind = $mainMod, RETURN, exec, kitty

# Close window
bind = ALT, F4, killactive
bind = $mainMod SHIFT, Q, killactive

# Reload config
bind = $mainMod SHIFT, C, exec, hyprctl reload

# Exit Hyprland
bind = $mainMod SHIFT, E, exit


# ---------------------
# Window movement
# ---------------------

# Focus windows
bind = $mainMod, LEFT, movefocus, l
bind = $mainMod, DOWN, movefocus, d
bind = $mainMod, UP, movefocus, u
bind = $mainMod, RIGHT, movefocus, r

# Move windows
bindm = $mainMod, mouse:272, movewindow
bind = $mainMod SHIFT, LEFT, movewindow, l
bind = $mainMod SHIFT, DOWN, movewindow, d
bind = $mainMod SHIFT, UP, movewindow, u
bind = $mainMod SHIFT, RIGHT, movewindow, r


# ---------------------
# Layouts
# ---------------------

# Horizontal split
bind = $mainMod, H, splitratio, -0.1

# Vertical split
bind = $mainMod, V, splitratio, 0.1

# Window grouping / tabs
bind = $mainMod, W, togglegroup

# Toggle fullscreen
bind = $mainMod, F, fullscreen

# Toggle split direction
bind = $mainMod, E, togglesplit

# Toggle floating
bind = $mainMod SHIFT, SPACE, togglefloating


# ---------------------
# Workspaces
# ---------------------

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

# Move window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5


# ---------------------
# Bar + wallpaper
# ---------------------

exec-once = waybar
exec-once = swaybg -i /home/imlost/Downloads/snow-pine-forest.png
exec-once = swayosd-server
exec-once = mako


# ---------------------
# Mouse behaviour
# ---------------------

$mainMod = SUPER

# ---------------------
# Appearance
# ---------------------

general {
    border_size = 2
    gaps_in = 8
    gaps_out = 4
}

# Pixel borders
decoration {
    rounding = 0
}

# ---------------------
# Floating dialogs
# ---------------------

windowrule = float, title:^(Open)$
windowrule = float, title:^(Save)$
windowrule = float, title:^(Save As)$
windowrule = float, title:^(Preferences)$
windowrule = float, title:^(File Upload)$


# ---------------------
# Input
# ---------------------

input {
    kb_layout = gb
}


# ---------------------
# Volume
# ---------------------

bind = , XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
bind = , XF86AudioLowerVolume, exec, swayosd-client --output-volume lower
bind = , XF86AudioMute, exec, swayosd-client --output-volume mute-toggle


# ---------------------
# Screenshot
# ---------------------

bind = , PRINT, exec, screenshot
